version: "3.8"

services:
  cashflow:
    build: .
    container_name: cashflow-web
    ports:
      - "9102:8000"
    volumes:
      - ./app:/app/app
      - /home/rahee/Web-Projects/cashflow-data/prod:/app/data
    restart: unless-stopped
