version: "3.8"

services:
  cashflow-staging:
    build: .
    container_name: cashflow-staging
    ports:
      - "9101:8000"
    environment:
      - CASHFLOW_DATA_DIR=/app/data
    volumes:
      - ./app:/app/app
      - /home/rahee/Web-Projects/cashflow-data/staging:/app/data
    restart: unless-stopped
